{application,vpn_bot,
             [{modules,['Elixir.VpnBot.Application','Elixir.VpnBot.Handler']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,ssl,inets,ex_gram,
                             jason,req]},
              {description,"vpn_bot"},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.VpnBot.Application',[]}}]}.
